spring.application.name=api-gateway
server.port=9090

# Customer Service
spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/customer/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# Medicine Service
spring.cloud.gateway.server.webflux.routes[1].id=medicine-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/medicine/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

# Cart Service
spring.cloud.gateway.server.webflux.routes[2].id=cart-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/cart/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1